import { createSlice } from '@reduxjs/toolkit'
import logger from '../utils/logger'
import serverService from '../services/server'
import toast from '../services/toast'

const mapSlice = createSlice({
  name:'map',
  initialState: '',
  reducers:{
    setMap(state, action){
      return action.payload
    },
    appendQuizResults(state, action){
      const node = state.prerequisites.find(n => n.id === action.payload.node.id)
      if (node) {
        node.test_finished = true
        node.passed = action.payload.passed
      }
    },
    clearMap(){
      return ''
    },
  }
})

// Export Autogenerated action creators
export const { clearMap } = mapSlice.actions

const { setMap, appendQuizResults } = mapSlice.actions

// Export redux-thunk for generating concept map and setting map in store
export const generateMap = (concept) => {
  return async (dispatch) => {
    //   setLoading({ state: true, type: 'map' })
    logger.info('Fetching map for:', concept)

    const result = await serverService.getMap(concept)
    if(result.success){
      logger.info('Concept map:', result.map)
      dispatch(setMap(result.map))
    } else {
      logger.error('Failed to generate map for:', concept)
      toast.show(result.error, 'error')
    }
    //   setLoading({ state:false })

  }
}

// Export redux-thunk for adding quiz results to current node
export const addQuizResults = (passed) => {
  return (dispatch, getState) => {
    const node = getState().currentNode
    logger.info('Adding results for node:', node)

    dispatch(appendQuizResults({ node, passed }))
  }
}

// Export reducer by default
export default mapSlice.reducer